Fix incompatible bug
ERROR:  Error installing rubygems-update:
There are no versions of rubygems-update (= 3.6.9) compatible with your Ruby & RubyGems
rubygems-update requires Ruby version >= 3.1.0. The current ruby version is 2.7.3.183.